#!/usr/bin/env python

import os
import scitran.data as scidata

acitivity = ''  # TODO
status = ''     # TODO

def dcm2nii(input, outbase=None):
    inpath = os.path.join('/input', input)
    ds = scidata.parse(inpath, filetype='dicom', load_data=True, ignore_json=True)

    if outbase is None:
        outbase = os.path.splitext(input)[0].rsplit('_', 1)[0] + 'nifti'
        outpath = os.path.join('/output', outbase)

    scidata.write(ds, ds.data, outbase=outpath, filetype='nifti')


if __name__ == '__main__':
    import argparse

    ap = argparse.ArgumentParser()
    ap.add_argument('input', help='input filename')
    ap.add_argument('outbase', help='output filename', nargs='?', default=None)

    args = ap.parse_args()

    dcm2nii(args.input, args.outbase)
