# Our version of ubuntu, prepared for any usage.

[image]
	name  = "flywheel.io/ubuntu-14.04"
	upstream = "index.docker.io/ubuntu-14.04"

[target.run]
	command = [ "/bin/bash" ]

[target.build]
	command = [ "/hroot/build.sh" ]

[target.bash]
	command = [ "/bin/bash" ]
