# DCM-Convert: convert DICOM files into other useful formats

[image]
	name  = "scitran.io/dcm-convert"
	upstream = "scitran.io/ubuntu-14.04"

[target.run]
	command = [ "/scripts/run" ]

[target.build]
	command = [ "/hroot/build.sh" ]

[target.bash]
	command = [ "/bin/bash" ]
