#! /bin/bash
#
# Run afq-demo
#
#
CONTAINER="[scitran/afq-demo]"

# Built to flywheel-v0 spec.
FLYWHEEL_BASE=/flywheel/v0

# Make sure that /output directory is empty (all content will be removed later).
OUTPUT_DIR=$FLYWHEEL_BASE/output

echo -e "$CONTAINER  Initiated"

if [[ ! -d "$OUTPUT_DIR" ]]
    then
        echo "$CONTAINER  $OUTPUT_DIR not found!"
        exit 1
fi

# Unzip AFQ demo data and move to output dir
cd $FLYWHEEL_BASE
unzip $FLYWHEEL_BASE/AFQ.zip
mv $FLYWHEEL_BASE/AFQ/* $OUTPUT_DIR

# Get a list of the files in the output directory
outputs=$(find $OUTPUT_DIR/* -maxdepth 0 -type f)

# If outputs exist, generate metadata and exit
if [[ -z $outputs ]]
    then
        echo "$CONTAINER  No results found in output directory... Exiting"
        exit 1
    else
        cd $OUTPUT_DIR
        $FLYWHEEL_BASE/metadata_create.py $OUTPUT_DIR
        echo -e "$CONTAINER  Wrote: `ls`"
        echo -e "$CONTAINER  Done!"
fi

exit 0


